{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dpgxvg6ylnefhcssr6xv7trytu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.25.jar",
          "url": "test-commit-revert-plugin-0.0.0.25.jar",
          "size": 6753,
          "sha512": "82fba92cf42b519ea2a623b788a88e853bdfa8f243b12e7ba86f40afa114f62f35149313433aa61f0ab0df8b31736eddc3e958554ff2a35c56e6eb99abee83df",
          "sha256": "9fc59fb02f71a533ac049eb34913f4634caed10158fd16bfe210fb3dae449c85",
          "sha1": "65eaaa88788a0d4fae1a9c48d27b29558eb0a8d9",
          "md5": "a3b34fc7a3d6bf100da4bcceebd12297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.25.jar",
          "url": "test-commit-revert-plugin-0.0.0.25.jar",
          "size": 6753,
          "sha512": "82fba92cf42b519ea2a623b788a88e853bdfa8f243b12e7ba86f40afa114f62f35149313433aa61f0ab0df8b31736eddc3e958554ff2a35c56e6eb99abee83df",
          "sha256": "9fc59fb02f71a533ac049eb34913f4634caed10158fd16bfe210fb3dae449c85",
          "sha1": "65eaaa88788a0d4fae1a9c48d27b29558eb0a8d9",
          "md5": "a3b34fc7a3d6bf100da4bcceebd12297"
        }
      ]
    }
  ]
}
