{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "nhni7yfseng2bebrgvvfg45gv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.33.jar",
          "url": "test-commit-revert-plugin-0.0.0.33.jar",
          "size": 6767,
          "sha512": "4c0f233486134a43c136b4673b6afcdd5920c7cb035c177c8e37c488c7a0d2ef1d7282979a4eebd38fcf8e2e535626fa3720ba6352d98f4d3046643da59534ed",
          "sha256": "409964b1f1b9f52dd39e24831c19baf60d227e05c7b96c1fd007dc538970b5f2",
          "sha1": "a864445dda512f72a55b1c51d1bebf60e6721c88",
          "md5": "076d6fd4067560fba4d2ef1dd5cf1abd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.33.jar",
          "url": "test-commit-revert-plugin-0.0.0.33.jar",
          "size": 6767,
          "sha512": "4c0f233486134a43c136b4673b6afcdd5920c7cb035c177c8e37c488c7a0d2ef1d7282979a4eebd38fcf8e2e535626fa3720ba6352d98f4d3046643da59534ed",
          "sha256": "409964b1f1b9f52dd39e24831c19baf60d227e05c7b96c1fd007dc538970b5f2",
          "sha1": "a864445dda512f72a55b1c51d1bebf60e6721c88",
          "md5": "076d6fd4067560fba4d2ef1dd5cf1abd"
        }
      ]
    }
  ]
}
