{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "nhni7yfseng2bebrgvvfg45gv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.33.jar",
          "url": "gradle-functional-test-api-0.0.0.33.jar",
          "size": 7849,
          "sha512": "6757ea834ce79df395c3b50eb0750eb474c31d727c989830d46bc0d01fc209ed406487c3066069edbb473d268caa769636f24597bc754bcfddaf32d2bda79863",
          "sha256": "ece354f94bcf559ebacf16ec553acedfb28b7bce2c3d4232b816c3b863c12d8b",
          "sha1": "45c8735d1af103a3e605ead2f8ed104acfd399ed",
          "md5": "f3bd01601b13bf99ea565aa91e74772b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.33.jar",
          "url": "gradle-functional-test-api-0.0.0.33.jar",
          "size": 7849,
          "sha512": "6757ea834ce79df395c3b50eb0750eb474c31d727c989830d46bc0d01fc209ed406487c3066069edbb473d268caa769636f24597bc754bcfddaf32d2bda79863",
          "sha256": "ece354f94bcf559ebacf16ec553acedfb28b7bce2c3d4232b816c3b863c12d8b",
          "sha1": "45c8735d1af103a3e605ead2f8ed104acfd399ed",
          "md5": "f3bd01601b13bf99ea565aa91e74772b"
        }
      ]
    }
  ]
}
