{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "wksyyqwhhzg5zozkzp47h4hzgm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.11.jar",
          "url": "gradle-functional-test-api-0.0.0.11.jar",
          "size": 7183,
          "sha512": "8b92b2b3515c9842e66859796f5957d2f134f205ad31479f9cf9ac3915f7aeef6bb322b918fced8ccdc76212d58fe23a99e31914d21d32e56ff0c3c6f716d391",
          "sha256": "fc903be6d6ae2188933331a5166dab228abf458e0067d2dd778ef6f0ad794aef",
          "sha1": "b11c61dfebc46042b7187d3f32e32ef4f0e5d67b",
          "md5": "a8f19b48bef4422db457ca1500cd5f72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.11.jar",
          "url": "gradle-functional-test-api-0.0.0.11.jar",
          "size": 7183,
          "sha512": "8b92b2b3515c9842e66859796f5957d2f134f205ad31479f9cf9ac3915f7aeef6bb322b918fced8ccdc76212d58fe23a99e31914d21d32e56ff0c3c6f716d391",
          "sha256": "fc903be6d6ae2188933331a5166dab228abf458e0067d2dd778ef6f0ad794aef",
          "sha1": "b11c61dfebc46042b7187d3f32e32ef4f0e5d67b",
          "md5": "a8f19b48bef4422db457ca1500cd5f72"
        }
      ]
    }
  ]
}
