{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vjissoqovrdz5dxsmq5dofwfge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.27.jar",
          "url": "gradle-functional-test-api-0.0.0.27.jar",
          "size": 7849,
          "sha512": "f50ada2726caa31226da490c30d5c9ed1bdb911eea5f0b22f5f9931f2555025733083d523eb6d2af794569c89601c61c0e5fb9eaa102294680cf425225597005",
          "sha256": "579e16b8c6885d58b59f86f5bf7647fce411a1cf8fc6c8a49d603864b0354c10",
          "sha1": "c93da2237b2b22ba6745a60a139e994e486d86c4",
          "md5": "888f865a636e233092cec164e0acc65e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.27.jar",
          "url": "gradle-functional-test-api-0.0.0.27.jar",
          "size": 7849,
          "sha512": "f50ada2726caa31226da490c30d5c9ed1bdb911eea5f0b22f5f9931f2555025733083d523eb6d2af794569c89601c61c0e5fb9eaa102294680cf425225597005",
          "sha256": "579e16b8c6885d58b59f86f5bf7647fce411a1cf8fc6c8a49d603864b0354c10",
          "sha1": "c93da2237b2b22ba6745a60a139e994e486d86c4",
          "md5": "888f865a636e233092cec164e0acc65e"
        }
      ]
    }
  ]
}
