{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "axjdb3wqrnc7loek7gjakrxyyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.17.jar",
          "url": "gradle-functional-test-api-0.0.0.17.jar",
          "size": 7849,
          "sha512": "2c0903e87f4ab84337d75a5fb5c4d1c5fa464abbb0efddd21ee5bb42ecd6fceb3d2308f489ce2a21b1e7c73dc331c39f8a6b86dd30f7f5bf0cd0e1adb325acc6",
          "sha256": "6cfc3ea5455a4121f6f175e147a350e001f7b0fbb2de17fa261bfe2da7bf2e1b",
          "sha1": "31a23f634564bb409c079a4b61181012f88edd5e",
          "md5": "c81674a4aa37824050774bcae4786c2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.17.jar",
          "url": "gradle-functional-test-api-0.0.0.17.jar",
          "size": 7849,
          "sha512": "2c0903e87f4ab84337d75a5fb5c4d1c5fa464abbb0efddd21ee5bb42ecd6fceb3d2308f489ce2a21b1e7c73dc331c39f8a6b86dd30f7f5bf0cd0e1adb325acc6",
          "sha256": "6cfc3ea5455a4121f6f175e147a350e001f7b0fbb2de17fa261bfe2da7bf2e1b",
          "sha1": "31a23f634564bb409c079a4b61181012f88edd5e",
          "md5": "c81674a4aa37824050774bcae4786c2a"
        }
      ]
    }
  ]
}
