{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "txwkthipxzhzpj32ifk45hhoye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.13.jar",
          "url": "test-commit-revert-plugin-0.0.0.13.jar",
          "size": 6753,
          "sha512": "daecdb0bebde755c42f1765e7025a5e1d38f26dcb74b431b4320096b8a19f068a27ebd5d4aeada755674279b14af1f26fe0bad63bfe354bc50cf5385817bbfcd",
          "sha256": "d7cff379dab6dca45a97fea639228ea4580ac53952e21697c95cecfc8a6c6fa1",
          "sha1": "b46621d2bd1ae4573fde546bad067244d2c49443",
          "md5": "951af4e17e3cc1007f68b70aa5a03a13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.13.jar",
          "url": "test-commit-revert-plugin-0.0.0.13.jar",
          "size": 6753,
          "sha512": "daecdb0bebde755c42f1765e7025a5e1d38f26dcb74b431b4320096b8a19f068a27ebd5d4aeada755674279b14af1f26fe0bad63bfe354bc50cf5385817bbfcd",
          "sha256": "d7cff379dab6dca45a97fea639228ea4580ac53952e21697c95cecfc8a6c6fa1",
          "sha1": "b46621d2bd1ae4573fde546bad067244d2c49443",
          "md5": "951af4e17e3cc1007f68b70aa5a03a13"
        }
      ]
    }
  ]
}
