{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "2zuvjxrayrbsdopeksul7wtu6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.31.jar",
          "url": "test-commit-revert-plugin-0.0.0.31.jar",
          "size": 6767,
          "sha512": "619d94f448dd9c6e40fe53f049aaaa7d0d21145f09abd8d8f64b44bb1b08114fe41461eedb8d2cc8b2bd16503fc03fb4fae55bce9f2f007cb87769e7ed7f1743",
          "sha256": "1bb702bca3e1f6a4854d2f6ded9f57c9f4afce10e936374ad12ee09ef59a732d",
          "sha1": "89eb6251e6758dcda3692b1f79020a3456baea2b",
          "md5": "1bfaa37b6c1a12085e1568f742b0fc79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.31.jar",
          "url": "test-commit-revert-plugin-0.0.0.31.jar",
          "size": 6767,
          "sha512": "619d94f448dd9c6e40fe53f049aaaa7d0d21145f09abd8d8f64b44bb1b08114fe41461eedb8d2cc8b2bd16503fc03fb4fae55bce9f2f007cb87769e7ed7f1743",
          "sha256": "1bb702bca3e1f6a4854d2f6ded9f57c9f4afce10e936374ad12ee09ef59a732d",
          "sha1": "89eb6251e6758dcda3692b1f79020a3456baea2b",
          "md5": "1bfaa37b6c1a12085e1568f742b0fc79"
        }
      ]
    }
  ]
}
