{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "install-distribution",
    "version": "0.0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vjissoqovrdz5dxsmq5dofwfge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.27.jar",
          "url": "install-distribution-0.0.0.27.jar",
          "size": 5106,
          "sha512": "a65d5b9019ff90c67a10b6c45dbb762b77a9065e03a7797a10c3703d82e2c05a25d428d11e4e164568d42a4cd67de6a1446717cb7111979ce338d3e85dff3221",
          "sha256": "a11caa13acd09e612bd7aafda9b88eac23e7b68a32258e60efd947ddb2e51892",
          "sha1": "f477d44669dddfe12d79d329be971f21e4632127",
          "md5": "8ebf480f39e3dd0505807dfc343532ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.27.jar",
          "url": "install-distribution-0.0.0.27.jar",
          "size": 5106,
          "sha512": "a65d5b9019ff90c67a10b6c45dbb762b77a9065e03a7797a10c3703d82e2c05a25d428d11e4e164568d42a4cd67de6a1446717cb7111979ce338d3e85dff3221",
          "sha256": "a11caa13acd09e612bd7aafda9b88eac23e7b68a32258e60efd947ddb2e51892",
          "sha1": "f477d44669dddfe12d79d329be971f21e4632127",
          "md5": "8ebf480f39e3dd0505807dfc343532ea"
        }
      ]
    }
  ]
}
