{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zieixltz2ncrth32k5zpnsaj4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.10.jar",
          "url": "gradle-functional-test-api-0.0.0.10.jar",
          "size": 7291,
          "sha512": "7983b902081b3876f920053590e4405630e2546617d74a935dc737c4a6f0200a234085add2b42840567411fff6e7b58979634aef8322ab41ba69ba6e9b64c862",
          "sha256": "54a7c8715f5d56abfacb5f778448d692a64af6001e5de9c98672acc5d4db24bf",
          "sha1": "9c34ed42f1dca11c6f39a65bb83e48c1f59ba58d",
          "md5": "f60dff645ab12981589e23c1fed9b386"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.10.jar",
          "url": "gradle-functional-test-api-0.0.0.10.jar",
          "size": 7291,
          "sha512": "7983b902081b3876f920053590e4405630e2546617d74a935dc737c4a6f0200a234085add2b42840567411fff6e7b58979634aef8322ab41ba69ba6e9b64c862",
          "sha256": "54a7c8715f5d56abfacb5f778448d692a64af6001e5de9c98672acc5d4db24bf",
          "sha1": "9c34ed42f1dca11c6f39a65bb83e48c1f59ba58d",
          "md5": "f60dff645ab12981589e23c1fed9b386"
        }
      ]
    }
  ]
}
