{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "install-distribution",
    "version": "0.0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "txwkthipxzhzpj32ifk45hhoye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.13.jar",
          "url": "install-distribution-0.0.0.13.jar",
          "size": 4829,
          "sha512": "43ce708b0880deb5a0946f9ae377b567fb53168253785a1538a0c203131b430df27cb50bafd9686ed4f01630c6b5880aed08dd3b5f24571ae6adf14d98dee721",
          "sha256": "8ebe41ca6ae0dba7323287432f853c6b5acca1ad22d8afa28a671631b7ea33b7",
          "sha1": "b73738a9b28d8dfcb10e7675b0e1a0316cd71dc4",
          "md5": "10d5b7d70883089486a094370f52955b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.13.jar",
          "url": "install-distribution-0.0.0.13.jar",
          "size": 4829,
          "sha512": "43ce708b0880deb5a0946f9ae377b567fb53168253785a1538a0c203131b430df27cb50bafd9686ed4f01630c6b5880aed08dd3b5f24571ae6adf14d98dee721",
          "sha256": "8ebe41ca6ae0dba7323287432f853c6b5acca1ad22d8afa28a671631b7ea33b7",
          "sha1": "b73738a9b28d8dfcb10e7675b0e1a0316cd71dc4",
          "md5": "10d5b7d70883089486a094370f52955b"
        }
      ]
    }
  ]
}
