{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "2zuvjxrayrbsdopeksul7wtu6y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.31.jar",
          "url": "gradle-functional-test-api-0.0.0.31.jar",
          "size": 7849,
          "sha512": "88754b09214d5c3e330395de5510f24c71afb739b21705e7e5d75c05c0ed9aa9649e2bdff258f8d730e3fc18337a7719876b5cb54df1d13ec1c977ac23d1c857",
          "sha256": "1b188824d4e18f3e12c4b02ed1cedc4e5f7ea558f39a179030612a68a81181aa",
          "sha1": "6085aab2dec2471dc3f6e401c3824e8a4fa03646",
          "md5": "d03850cdd9a7e4701e2d49750dcff65e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.31.jar",
          "url": "gradle-functional-test-api-0.0.0.31.jar",
          "size": 7849,
          "sha512": "88754b09214d5c3e330395de5510f24c71afb739b21705e7e5d75c05c0ed9aa9649e2bdff258f8d730e3fc18337a7719876b5cb54df1d13ec1c977ac23d1c857",
          "sha256": "1b188824d4e18f3e12c4b02ed1cedc4e5f7ea558f39a179030612a68a81181aa",
          "sha1": "6085aab2dec2471dc3f6e401c3824e8a4fa03646",
          "md5": "d03850cdd9a7e4701e2d49750dcff65e"
        }
      ]
    }
  ]
}
