{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "frx47ru4yrb4tb4wpo3dhkvgxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.15.jar",
          "url": "gradle-functional-test-api-0.0.0.15.jar",
          "size": 7849,
          "sha512": "0c25c89ab11a845e0d4e2f0414acc1e17859cc4dcb9798aff202f78acba9b0e1e6bf30b1895c9b39171aa6c437283bb49f83bfaea5bdbf2dbc8843d5ab07ddb4",
          "sha256": "fa496ce0b9fb49091b83f725d0261fd8fee2b8a7959f881bdf2336c209a2954c",
          "sha1": "e80bef971f188b822cdb230b78b49094c645a16b",
          "md5": "b04dc65a774e043b8623b58c8aaa4f42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.15.jar",
          "url": "gradle-functional-test-api-0.0.0.15.jar",
          "size": 7849,
          "sha512": "0c25c89ab11a845e0d4e2f0414acc1e17859cc4dcb9798aff202f78acba9b0e1e6bf30b1895c9b39171aa6c437283bb49f83bfaea5bdbf2dbc8843d5ab07ddb4",
          "sha256": "fa496ce0b9fb49091b83f725d0261fd8fee2b8a7959f881bdf2336c209a2954c",
          "sha1": "e80bef971f188b822cdb230b78b49094c645a16b",
          "md5": "b04dc65a774e043b8623b58c8aaa4f42"
        }
      ]
    }
  ]
}
