{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "wqkbfimdrneqljjlo4jlqzfwam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.35.jar",
          "url": "test-commit-revert-plugin-0.0.0.35.jar",
          "size": 6769,
          "sha512": "d84b66d27c73f64b41669c14102d82f672d8b8d2a337f57b777ba2fed27ffbd6b3a6b01dfc9911aa6f57d838c498d204f8b53f38e7e20dce5af46538129f5ce7",
          "sha256": "e68850d8448ef16268dead9d987512538186a6e68d3834ce87efaaeb3713ea85",
          "sha1": "c16ed768aa3f28be11a320d517a38e34e03cd9bc",
          "md5": "9e5c6e2e5db5000290a29dec1315ce43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.35.jar",
          "url": "test-commit-revert-plugin-0.0.0.35.jar",
          "size": 6769,
          "sha512": "d84b66d27c73f64b41669c14102d82f672d8b8d2a337f57b777ba2fed27ffbd6b3a6b01dfc9911aa6f57d838c498d204f8b53f38e7e20dce5af46538129f5ce7",
          "sha256": "e68850d8448ef16268dead9d987512538186a6e68d3834ce87efaaeb3713ea85",
          "sha1": "c16ed768aa3f28be11a320d517a38e34e03cd9bc",
          "md5": "9e5c6e2e5db5000290a29dec1315ce43"
        }
      ]
    }
  ]
}
