{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "txwkthipxzhzpj32ifk45hhoye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.13.jar",
          "url": "gradle-functional-test-api-0.0.0.13.jar",
          "size": 7849,
          "sha512": "92df3474e09b43071e366d9bc796d2e05cad7cc783a42cbbbeded897489523d336e5ff16b99813198e315283628d1469234f27f992c08175a57c10ce41f04143",
          "sha256": "68db7a5830ae7be106ea0d655e0008fec5109f920ccfa10d918b5d0fad119c6d",
          "sha1": "3ba565bb88d5ad9431aeaa69f1f4b955597c9304",
          "md5": "9407663a41b9125447da7c6383bb5ba0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.13.jar",
          "url": "gradle-functional-test-api-0.0.0.13.jar",
          "size": 7849,
          "sha512": "92df3474e09b43071e366d9bc796d2e05cad7cc783a42cbbbeded897489523d336e5ff16b99813198e315283628d1469234f27f992c08175a57c10ce41f04143",
          "sha256": "68db7a5830ae7be106ea0d655e0008fec5109f920ccfa10d918b5d0fad119c6d",
          "sha1": "3ba565bb88d5ad9431aeaa69f1f4b955597c9304",
          "md5": "9407663a41b9125447da7c6383bb5ba0"
        }
      ]
    }
  ]
}
