{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "dpgxvg6ylnefhcssr6xv7trytu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.25.jar",
          "url": "gradle-functional-test-api-0.0.0.25.jar",
          "size": 7849,
          "sha512": "e34667580701dfcb86c2c96c0aaaba2b6ec994ff73960fbaa245bc6c68cf01fdbcae3a5922ece522313709cbc443ff916ce7d5b02244b0ed907f1a6111ad0ba3",
          "sha256": "df0bc06dd31f8d24c53c3b2301355526c10f211c33b490b6ac058abe3d38a6d9",
          "sha1": "26301d114e697aa67bf54ed629dc5918983c71d4",
          "md5": "0d014d236c58cdd3678b1ece743c7191"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.25.jar",
          "url": "gradle-functional-test-api-0.0.0.25.jar",
          "size": 7849,
          "sha512": "e34667580701dfcb86c2c96c0aaaba2b6ec994ff73960fbaa245bc6c68cf01fdbcae3a5922ece522313709cbc443ff916ce7d5b02244b0ed907f1a6111ad0ba3",
          "sha256": "df0bc06dd31f8d24c53c3b2301355526c10f211c33b490b6ac058abe3d38a6d9",
          "sha1": "26301d114e697aa67bf54ed629dc5918983c71d4",
          "md5": "0d014d236c58cdd3678b1ece743c7191"
        }
      ]
    }
  ]
}
