{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "c4e5w35sxzh7xogq3l4yiydeja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.6.jar",
          "url": "gradle-functional-test-api-0.0.0.6.jar",
          "size": 7210,
          "sha512": "de9867caeb6acf724e9482e5d90230ff5ca2d7ca4adefa811d4e926b9cd5bf35621b9468f631782bb5d29b1460ea1e279b8df569aa47ffa60755a69458e97d41",
          "sha256": "1a3327c2692e20a940828bfa68cb89c9a6bc346d4b96f43d93643efbf67fdafa",
          "sha1": "7190f1a8dedd8043414376479a0ea78add11baa9",
          "md5": "5fda23cf9ac77487e149367078f6d68f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.6.jar",
          "url": "gradle-functional-test-api-0.0.0.6.jar",
          "size": 7210,
          "sha512": "de9867caeb6acf724e9482e5d90230ff5ca2d7ca4adefa811d4e926b9cd5bf35621b9468f631782bb5d29b1460ea1e279b8df569aa47ffa60755a69458e97d41",
          "sha256": "1a3327c2692e20a940828bfa68cb89c9a6bc346d4b96f43d93643efbf67fdafa",
          "sha1": "7190f1a8dedd8043414376479a0ea78add11baa9",
          "md5": "5fda23cf9ac77487e149367078f6d68f"
        }
      ]
    }
  ]
}
