{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "install-distribution",
    "version": "0.0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xddtosme6bcqfiz6tx64hfxcm4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.23.jar",
          "url": "install-distribution-0.0.0.23.jar",
          "size": 5078,
          "sha512": "8ac8f906cc14e35babe60d0308d8214ba727ad501ab1fd70b67c8fab8555b22ea30cac19bda770af835652ec51571372050f096fa1bd7870166e465e81877e46",
          "sha256": "20ddb4320f5f42b7c25a97df652433d0e411a083beeb1e4ab8a278ea82b359a8",
          "sha1": "dcb29876350c5824cb22ccf6427103edf1f55b25",
          "md5": "95ee9c81dcf9d552525698c4b3a3d1f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.23.jar",
          "url": "install-distribution-0.0.0.23.jar",
          "size": 5078,
          "sha512": "8ac8f906cc14e35babe60d0308d8214ba727ad501ab1fd70b67c8fab8555b22ea30cac19bda770af835652ec51571372050f096fa1bd7870166e465e81877e46",
          "sha256": "20ddb4320f5f42b7c25a97df652433d0e411a083beeb1e4ab8a278ea82b359a8",
          "sha1": "dcb29876350c5824cb22ccf6427103edf1f55b25",
          "md5": "95ee9c81dcf9d552525698c4b3a3d1f7"
        }
      ]
    }
  ]
}
