{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iqpxsjdzezbdnlrujeamzq4oha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.29.jar",
          "url": "test-commit-revert-plugin-0.0.0.29.jar",
          "size": 6753,
          "sha512": "1f692077015e2d75c742275d5cde7fa3e097ba6ab7305b9faa0d6224cefe787e9182ef713e402886476c95944d22b8c547f1510740a11ce94f41e44334eb6c95",
          "sha256": "c25ed9064c5922134084764b7778b55ed263c818267c157ce9fde3a5b57dde38",
          "sha1": "5c98398e590910210f34df8eb5596792dccc83cc",
          "md5": "3b4decf1d46dec28db1b78163c90d445"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.29.jar",
          "url": "test-commit-revert-plugin-0.0.0.29.jar",
          "size": 6753,
          "sha512": "1f692077015e2d75c742275d5cde7fa3e097ba6ab7305b9faa0d6224cefe787e9182ef713e402886476c95944d22b8c547f1510740a11ce94f41e44334eb6c95",
          "sha256": "c25ed9064c5922134084764b7778b55ed263c818267c157ce9fde3a5b57dde38",
          "sha1": "5c98398e590910210f34df8eb5596792dccc83cc",
          "md5": "3b4decf1d46dec28db1b78163c90d445"
        }
      ]
    }
  ]
}
