{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zieixltz2ncrth32k5zpnsaj4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.10.jar",
          "url": "test-commit-revert-plugin-0.0.0.10.jar",
          "size": 6753,
          "sha512": "9349b28a030e6f0aa11dc407fbeae82a2c879c7e151a6dbf438e083df9b2a848ddb9edd32c268bf26b0ee602bb931df418f15b7a76b4f22653e4f883052c84a8",
          "sha256": "fde20e2ed6455a93948d1e29216dbb0329dcd3406859d11e05bcb9eff63d1b1f",
          "sha1": "479369086f6c69a4b2de34ba2087a6b45ba47c74",
          "md5": "e2266ae4ffaa3302997331200c09c64a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.10.jar",
          "url": "test-commit-revert-plugin-0.0.0.10.jar",
          "size": 6753,
          "sha512": "9349b28a030e6f0aa11dc407fbeae82a2c879c7e151a6dbf438e083df9b2a848ddb9edd32c268bf26b0ee602bb931df418f15b7a76b4f22653e4f883052c84a8",
          "sha256": "fde20e2ed6455a93948d1e29216dbb0329dcd3406859d11e05bcb9eff63d1b1f",
          "sha1": "479369086f6c69a4b2de34ba2087a6b45ba47c74",
          "md5": "e2266ae4ffaa3302997331200c09c64a"
        }
      ]
    }
  ]
}
