{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert",
    "version": "0.0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "c4e5w35sxzh7xogq3l4yiydeja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-0.0.0.6.jar",
          "url": "test-commit-revert-0.0.0.6.jar",
          "size": 5641,
          "sha512": "9c7399b033d7c7015c006550b60fc1ea40cd105925438c3aa0caf83879ccfc0f33ce7598a75d32f8fe2f4189064aee045fdbe32c1666381a5e8a5aa5f6b5d5fb",
          "sha256": "8bfb3d640ca637cfce2aed1be1a6cf894180986319ba777692845d84e5000e12",
          "sha1": "e8c4448115b61b1f3fdbe19ee6bd6b474d256c0e",
          "md5": "363e7bdc20ea14e52eff7ac882807cc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-commit-revert-0.0.0.6.jar",
          "url": "test-commit-revert-0.0.0.6.jar",
          "size": 5641,
          "sha512": "9c7399b033d7c7015c006550b60fc1ea40cd105925438c3aa0caf83879ccfc0f33ce7598a75d32f8fe2f4189064aee045fdbe32c1666381a5e8a5aa5f6b5d5fb",
          "sha256": "8bfb3d640ca637cfce2aed1be1a6cf894180986319ba777692845d84e5000e12",
          "sha1": "e8c4448115b61b1f3fdbe19ee6bd6b474d256c0e",
          "md5": "363e7bdc20ea14e52eff7ac882807cc1"
        }
      ]
    }
  ]
}
