{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "spring-console-api",
    "version": "0.0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "7j35la3gnzh25ngjxxvz62uftm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-console-api-0.0.0.33.jar",
          "url": "spring-console-api-0.0.0.33.jar",
          "size": 261,
          "sha512": "88e26dde02c50193e15ad4360e6624d5700f50ea98711015d3c09eccdf8ec8e4070bb15836bf0bf7d0954a09c985f85a45369cc5e252fa4a41fc251cac3db4a6",
          "sha256": "64a18fa365acf91e92836128041ac5a5d3699352cdd19e3d5d5d76b0e1442cab",
          "sha1": "19e541c143dd3e899d763b20e854e84cda065ee7",
          "md5": "e3d14f4407726c15a7d6635fed354fef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-console-api-0.0.0.33.jar",
          "url": "spring-console-api-0.0.0.33.jar",
          "size": 261,
          "sha512": "88e26dde02c50193e15ad4360e6624d5700f50ea98711015d3c09eccdf8ec8e4070bb15836bf0bf7d0954a09c985f85a45369cc5e252fa4a41fc251cac3db4a6",
          "sha256": "64a18fa365acf91e92836128041ac5a5d3699352cdd19e3d5d5d76b0e1442cab",
          "sha1": "19e541c143dd3e899d763b20e854e84cda065ee7",
          "md5": "e3d14f4407726c15a7d6635fed354fef"
        }
      ]
    }
  ]
}
