{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "test-commit-revert-plugin",
    "version": "0.0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "stnl2wbecfhh7o4athkgi2izem"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.34.jar",
          "url": "test-commit-revert-plugin-0.0.0.34.jar",
          "size": 6767,
          "sha512": "8920c171798d5eba2d3f29b16a329d6fdd66edb1787b2393ebc11b54456ac692e73c9fbe4e287bedb0351190a3179cf207ec9df9db91776cbe649651d954935e",
          "sha256": "6e88b0bf374a45cd37d4e302a6d72b183b39cd88061c14b49047095e41feecb4",
          "sha1": "2ac73d08b8bd31f9419d413efe7916917c69b3ca",
          "md5": "6575bb5076bc0e1651d06f2e4261cb5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        }
      ],
      "files": [
        {
          "name": "test-commit-revert-plugin-0.0.0.34.jar",
          "url": "test-commit-revert-plugin-0.0.0.34.jar",
          "size": 6767,
          "sha512": "8920c171798d5eba2d3f29b16a329d6fdd66edb1787b2393ebc11b54456ac692e73c9fbe4e287bedb0351190a3179cf207ec9df9db91776cbe649651d954935e",
          "sha256": "6e88b0bf374a45cd37d4e302a6d72b183b39cd88061c14b49047095e41feecb4",
          "sha1": "2ac73d08b8bd31f9419d413efe7916917c69b3ca",
          "md5": "6575bb5076bc0e1651d06f2e4261cb5c"
        }
      ]
    }
  ]
}
