{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "install-distribution",
    "version": "0.0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "iqpxsjdzezbdnlrujeamzq4oha"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.29.jar",
          "url": "install-distribution-0.0.0.29.jar",
          "size": 5038,
          "sha512": "3700667f142e6e53673b8094318c45bd21ef33f566b338ba1ac9c499722e047cbbe6b8b8ec4cae1417ac4a2c853537d9f1411cf8b5500dcec4d52f2f7a2012cb",
          "sha256": "532e9ec2579f3b6b45450f00105d05522d9853eab97988571b7fa5daf30937ac",
          "sha1": "06fa7b150b0861002a06cc3784ba4a26ac400b86",
          "md5": "fe1df0814e0145856a841740966c0d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "install-distribution-0.0.0.29.jar",
          "url": "install-distribution-0.0.0.29.jar",
          "size": 5038,
          "sha512": "3700667f142e6e53673b8094318c45bd21ef33f566b338ba1ac9c499722e047cbbe6b8b8ec4cae1417ac4a2c853537d9f1411cf8b5500dcec4d52f2f7a2012cb",
          "sha256": "532e9ec2579f3b6b45450f00105d05522d9853eab97988571b7fa5daf30937ac",
          "sha1": "06fa7b150b0861002a06cc3784ba4a26ac400b86",
          "md5": "fe1df0814e0145856a841740966c0d9c"
        }
      ]
    }
  ]
}
