{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.mfisch2011",
    "module": "gradle-functional-test-api",
    "version": "0.0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3seywc7fhrh77mvv6xjsw5xhyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.19.jar",
          "url": "gradle-functional-test-api-0.0.0.19.jar",
          "size": 7849,
          "sha512": "b632cf51b9cc9b3dffacb1be91548a5cade25e1c2275a59cbdf9a2bad272bcbb429c00401b0da75d46517e53790f2e4bc0a1363b5c6a768a0d63a0907e9be10e",
          "sha256": "17df9fffb603a78d5225a5cde448e42f934760feaeb5cc5a23d087e105889e1d",
          "sha1": "1d4266ec4fbb8a1a9c25241ba2456d0861b4daa9",
          "md5": "5865481b5b6ddc67749940bdae308b36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-functional-test-api-0.0.0.19.jar",
          "url": "gradle-functional-test-api-0.0.0.19.jar",
          "size": 7849,
          "sha512": "b632cf51b9cc9b3dffacb1be91548a5cade25e1c2275a59cbdf9a2bad272bcbb429c00401b0da75d46517e53790f2e4bc0a1363b5c6a768a0d63a0907e9be10e",
          "sha256": "17df9fffb603a78d5225a5cde448e42f934760feaeb5cc5a23d087e105889e1d",
          "sha1": "1d4266ec4fbb8a1a9c25241ba2456d0861b4daa9",
          "md5": "5865481b5b6ddc67749940bdae308b36"
        }
      ]
    }
  ]
}
